// Categorized emoji list
export const emojiCategories = [
	{
		name: "Faces",
		emojis: [
			{ emoji: "😀", code: ":grinning:" },
			{ emoji: "😂", code: ":joy:" },
			{ emoji: "😍", code: ":heart_eyes:" },
			{ emoji: "🤔", code: ":thinking:" },
			{ emoji: "😊", code: ":blush:" },
			{ emoji: "😢", code: ":cry:" },
			{ emoji: "😎", code: ":sunglasses:" },
			{ emoji: "😴", code: ":sleeping:" },
			{ emoji: "🤗", code: ":hugs:" },
			{ emoji: "😋", code: ":yum:" },
			{ emoji: "🙄", code: ":roll_eyes:" },
			{ emoji: "😅", code: ":sweat_smile:" },
			{ emoji: "🤷", code: ":shrug:" },
			{ emoji: "😃", code: ":smiley:" },
			{ emoji: "😄", code: ":smile:" },
			{ emoji: "😁", code: ":grin:" },
			{ emoji: "😆", code: ":laughing:" },
			{ emoji: "🤣", code: ":rofl:" },
			{ emoji: "😇", code: ":innocent:" },
			{ emoji: "🙂", code: ":slightly_smiling_face:" },
			{ emoji: "🙃", code: ":upside_down_face:" },
			{ emoji: "😉", code: ":wink:" },
			{ emoji: "😌", code: ":relieved:" },
			{ emoji: "🥰", code: ":smiling_face_with_hearts:" },
			{ emoji: "😘", code: ":kissing_heart:" },
			{ emoji: "😗", code: ":kissing:" },
			{ emoji: "😙", code: ":kissing_smiling_eyes:" },
			{ emoji: "😚", code: ":kissing_closed_eyes:" },
			{ emoji: "😛", code: ":stuck_out_tongue:" },
			{ emoji: "😜", code: ":stuck_out_tongue_winking_eye:" },
			{ emoji: "🤪", code: ":zany_face:" },
			{ emoji: "😝", code: ":stuck_out_tongue_closed_eyes:" },
			{ emoji: "🤑", code: ":money_mouth_face:" },
			{ emoji: "🤭", code: ":hand_over_mouth:" },
			{ emoji: "🤫", code: ":shushing_face:" },
			{ emoji: "🤐", code: ":zipper_mouth_face:" },
			{ emoji: "🤨", code: ":raised_eyebrow:" },
			{ emoji: "😐", code: ":neutral_face:" },
			{ emoji: "😑", code: ":expressionless:" },
			{ emoji: "😶", code: ":no_mouth:" },
			{ emoji: "😏", code: ":smirk:" },
			{ emoji: "😒", code: ":unamused:" },
			{ emoji: "😬", code: ":grimacing:" },
			{ emoji: "🤥", code: ":lying_face:" },
		],
	},
	{
		name: "Gestures",
		emojis: [
			{ emoji: "👍", code: ":+1:" },
			{ emoji: "👎", code: ":-1:" },
			{ emoji: "👏", code: ":clap:" },
			{ emoji: "🙏", code: ":pray:" },
			{ emoji: "💪", code: ":muscle:" },
			{ emoji: "✌️", code: ":v:" },
			{ emoji: "🤝", code: ":handshake:" },
			{ emoji: "👋", code: ":wave:" },
			{ emoji: "👌", code: ":ok_hand:" },
			{ emoji: "🤞", code: ":crossed_fingers:" },
			{ emoji: "🤟", code: ":love_you_gesture:" },
			{ emoji: "🤘", code: ":metal:" },
			{ emoji: "🤙", code: ":call_me_hand:" },
			{ emoji: "👈", code: ":point_left:" },
			{ emoji: "👉", code: ":point_right:" },
			{ emoji: "👆", code: ":point_up_2:" },
			{ emoji: "👇", code: ":point_down:" },
			{ emoji: "☝️", code: ":point_up:" },
			{ emoji: "🤚", code: ":raised_back_of_hand:" },
			{ emoji: "🖐️", code: ":raised_hand_with_fingers_splayed:" },
			{ emoji: "✋", code: ":hand:" },
			{ emoji: "🖖", code: ":vulcan_salute:" },
			{ emoji: "🙌", code: ":raised_hands:" },
			{ emoji: "👐", code: ":open_hands:" },
			{ emoji: "🤲", code: ":palms_up_together:" },
			{ emoji: "✍️", code: ":writing_hand:" },
			{ emoji: "🦾", code: ":mechanical_arm:" },
			{ emoji: "🦿", code: ":mechanical_leg:" },
			{ emoji: "🦵", code: ":leg:" },
			{ emoji: "🦶", code: ":foot:" },
			{ emoji: "👂", code: ":ear:" },
			{ emoji: "🦻", code: ":ear_with_hearing_aid:" },
			{ emoji: "👃", code: ":nose:" },
			{ emoji: "🧠", code: ":brain:" },
			{ emoji: "🫀", code: ":anatomical_heart:" },
			{ emoji: "🫁", code: ":lungs:" },
			{ emoji: "🦷", code: ":tooth:" },
			{ emoji: "🦴", code: ":bone:" },
			{ emoji: "👀", code: ":eyes:" },
			{ emoji: "👁️", code: ":eye:" },
		],
	},
	{
		name: "Hearts",
		emojis: [
			{ emoji: "❤️", code: ":heart:" },
			{ emoji: "💙", code: ":blue_heart:" },
			{ emoji: "💚", code: ":green_heart:" },
			{ emoji: "💛", code: ":yellow_heart:" },
			{ emoji: "🧡", code: ":orange_heart:" },
			{ emoji: "💜", code: ":purple_heart:" },
			{ emoji: "🖤", code: ":black_heart:" },
			{ emoji: "💔", code: ":broken_heart:" },
			{ emoji: "🤍", code: ":white_heart:" },
			{ emoji: "🤎", code: ":brown_heart:" },
			{ emoji: "❣️", code: ":heavy_heart_exclamation:" },
			{ emoji: "💕", code: ":two_hearts:" },
			{ emoji: "💞", code: ":revolving_hearts:" },
			{ emoji: "💓", code: ":heartbeat:" },
			{ emoji: "💗", code: ":heartpulse:" },
			{ emoji: "💖", code: ":sparkling_heart:" },
			{ emoji: "💘", code: ":cupid:" },
			{ emoji: "💝", code: ":gift_heart:" },
			{ emoji: "💟", code: ":heart_decoration:" },
			{ emoji: "♥️", code: ":hearts:" },
			{ emoji: "💌", code: ":love_letter:" },
			{ emoji: "💋", code: ":kiss:" },
			{ emoji: "💍", code: ":ring:" },
			{ emoji: "💎", code: ":gem:" },
			{ emoji: "🌹", code: ":rose:" },
			{ emoji: "🌺", code: ":hibiscus:" },
			{ emoji: "🌻", code: ":sunflower:" },
			{ emoji: "🌷", code: ":tulip:" },
			{ emoji: "🌸", code: ":cherry_blossom:" },
			{ emoji: "💐", code: ":bouquet:" },
			{ emoji: "🎀", code: ":ribbon:" },
			{ emoji: "🎁", code: ":gift:" },
			{ emoji: "🍫", code: ":chocolate_bar:" },
			{ emoji: "🍰", code: ":cake:" },
			{ emoji: "🧁", code: ":cupcake:" },
			{ emoji: "🍭", code: ":lollipop:" },
			{ emoji: "🍬", code: ":candy:" },
			{ emoji: "🍯", code: ":honey_pot:" },
			{ emoji: "🥂", code: ":clinking_glasses:" },
			{ emoji: "🍾", code: ":champagne:" },
		],
	},
	{
		name: "Objects",
		emojis: [
			{ emoji: "🔥", code: ":fire:" },
			{ emoji: "💯", code: ":100:" },
			{ emoji: "🎉", code: ":tada:" },
			{ emoji: "🚀", code: ":rocket:" },
			{ emoji: "⭐", code: ":star:" },
			{ emoji: "💎", code: ":gem:" },
			{ emoji: "🎯", code: ":dart:" },
			{ emoji: "🏆", code: ":trophy:" },
			{ emoji: "📱", code: ":iphone:" },
			{ emoji: "💻", code: ":computer:" },
			{ emoji: "⌨️", code: ":keyboard:" },
			{ emoji: "🖥️", code: ":desktop_computer:" },
			{ emoji: "🖨️", code: ":printer:" },
			{ emoji: "🖱️", code: ":computer_mouse:" },
			{ emoji: "🖲️", code: ":trackball:" },
			{ emoji: "💽", code: ":minidisc:" },
			{ emoji: "💾", code: ":floppy_disk:" },
			{ emoji: "💿", code: ":cd:" },
			{ emoji: "📀", code: ":dvd:" },
			{ emoji: "📼", code: ":vhs:" },
			{ emoji: "📷", code: ":camera:" },
			{ emoji: "📸", code: ":camera_flash:" },
			{ emoji: "📹", code: ":video_camera:" },
			{ emoji: "🎥", code: ":movie_camera:" },
			{ emoji: "📞", code: ":telephone_receiver:" },
			{ emoji: "☎️", code: ":phone:" },
			{ emoji: "📟", code: ":pager:" },
			{ emoji: "📠", code: ":fax:" },
			{ emoji: "📺", code: ":tv:" },
			{ emoji: "📻", code: ":radio:" },
			{ emoji: "🎙️", code: ":studio_microphone:" },
			{ emoji: "🎚️", code: ":level_slider:" },
			{ emoji: "🎛️", code: ":control_knobs:" },
			{ emoji: "🧭", code: ":compass:" },
			{ emoji: "⏰", code: ":alarm_clock:" },
			{ emoji: "⏲️", code: ":timer_clock:" },
			{ emoji: "⏱️", code: ":stopwatch:" },
			{ emoji: "⏳", code: ":hourglass_flowing_sand:" },
			{ emoji: "📡", code: ":satellite:" },
			{ emoji: "🔋", code: ":battery:" },
			{ emoji: "🔌", code: ":electric_plug:" },
			{ emoji: "💡", code: ":bulb:" },
			{ emoji: "🔦", code: ":flashlight:" },
			{ emoji: "🕯️", code: ":candle:" },
			{ emoji: "🪔", code: ":diya_lamp:" },
			{ emoji: "🧯", code: ":fire_extinguisher:" },
			{ emoji: "🛢️", code: ":oil_drum:" },
			{ emoji: "💸", code: ":money_with_wings:" },
			{ emoji: "💰", code: ":moneybag:" },
		],
	},
	{
		name: "Software",
		emojis: [
			{ emoji: "💻", code: ":computer:" },
			{ emoji: "🖥️", code: ":desktop_computer:" },
			{ emoji: "⌨️", code: ":keyboard:" },
			{ emoji: "🖱️", code: ":computer_mouse:" },
			{ emoji: "💾", code: ":floppy_disk:" },
			{ emoji: "💿", code: ":cd:" },
			{ emoji: "📀", code: ":dvd:" },
			{ emoji: "💽", code: ":minidisc:" },
			{ emoji: "🖲️", code: ":trackball:" },
			{ emoji: "📱", code: ":iphone:" },
			{ emoji: "⚙️", code: ":gear:" },
			{ emoji: "🔧", code: ":wrench:" },
			{ emoji: "🔨", code: ":hammer:" },
			{ emoji: "🛠️", code: ":hammer_and_wrench:" },
			{ emoji: "⚡", code: ":zap:" },
			{ emoji: "🔌", code: ":electric_plug:" },
			{ emoji: "💡", code: ":bulb:" },
			{ emoji: "🔍", code: ":mag:" },
			{ emoji: "🔎", code: ":mag_right:" },
			{ emoji: "📊", code: ":bar_chart:" },
			{ emoji: "📈", code: ":chart_with_upwards_trend:" },
			{ emoji: "📉", code: ":chart_with_downwards_trend:" },
			{ emoji: "🗂️", code: ":card_index_dividers:" },
			{ emoji: "📁", code: ":file_folder:" },
			{ emoji: "📂", code: ":open_file_folder:" },
			{ emoji: "🗃️", code: ":card_file_box:" },
			{ emoji: "🗄️", code: ":file_cabinet:" },
			{ emoji: "📋", code: ":clipboard:" },
			{ emoji: "📌", code: ":pushpin:" },
			{ emoji: "📍", code: ":round_pushpin:" },
			{ emoji: "📎", code: ":paperclip:" },
			{ emoji: "🖇️", code: ":paperclips:" },
			{ emoji: "📏", code: ":straight_ruler:" },
			{ emoji: "📐", code: ":triangular_ruler:" },
			{ emoji: "✂️", code: ":scissors:" },
			{ emoji: "🗑️", code: ":wastebasket:" },
			{ emoji: "🔒", code: ":lock:" },
			{ emoji: "🔓", code: ":unlock:" },
			{ emoji: "🔑", code: ":key:" },
			{ emoji: "🚀", code: ":rocket:" },
			{ emoji: "🔥", code: ":fire:" },
			{ emoji: "💯", code: ":100:" },
			{ emoji: "⭐", code: ":star:" },
			{ emoji: "🎯", code: ":dart:" },
			{ emoji: "🏆", code: ":trophy:" },
			{ emoji: "🎉", code: ":tada:" },
			{ emoji: "🔋", code: ":battery:" },
			{ emoji: "📡", code: ":satellite:" },
			{ emoji: "🌐", code: ":globe_with_meridians:" },
			{ emoji: "🔗", code: ":link:" },
			{ emoji: "📧", code: ":email:" },
			{ emoji: "📨", code: ":incoming_envelope:" },
			{ emoji: "📩", code: ":envelope_with_arrow:" },
			{ emoji: "📤", code: ":outbox_tray:" },
			{ emoji: "📥", code: ":inbox_tray:" },
			{ emoji: "📦", code: ":package:" },
			{ emoji: "📮", code: ":postbox:" },
			{ emoji: "🖨️", code: ":printer:" },
			{ emoji: "💻", code: ":laptop:" },
			{ emoji: "🖥️", code: ":desktop:" },
			{ emoji: "📟", code: ":pager:" },
			{ emoji: "📠", code: ":fax:" },
		],
	},
];

// Types of emoji categories
export interface EmojiItem {
	emoji: string;
	code: string;
}

export interface EmojiCategory {
	name: string;
	emojis: EmojiItem[];
}

export interface DiagramType {
	name: string;
	template: string;
}
